print("Perhitungan (a+b)(a-c)")
print("========================")
a = int(input("Masukkan Nilai a :"))
b = int(input("Masukkan Nilai b :"))
c =int(input("Masukkan Nilai c :"))
print("========================")
print("(a+b)(a-c)")
print("a:",a)
print("b:",b)
print("c:",c)
print("Hasil dari (a+b)(a-c) :", (a+b)*(a-c))
print("========================")

print("Perhitungan (a)(b)/(a+c)")
print("========================")
a = int(input("Masukkan Nilai a :"))
b= int(input("Masukkan Nilai b :"))
c = int(input("Masukkan Nilai c :"))
print("========================")
print("(a)(b)/(a+c)")
print("a:",a)
print("b:",b)
print("c:",c)
print("Hasil dari (a)(b)/(a+c) adalah :",(a*b)/(a+c))
print("========================")

print("Perhitungan Luas Trapesium")
print("========================")
a = int(input("Masukkan Nilai a :"))
b = int(input("Masukkan Nilai b :"))
t = int(input("Masukkan Nilai t :"))
print("========================")
print("Luas Trapesium")
print("a:",a)
print("b:",b)
print("t:",t) 
print("Rumus trapesium yaitu 1/2 (a+b) t")
print("Jadi hasil dari luas trapesium adalah:",1/2*(a+b)*t) 
print("========================")

print("Perhitungan Keliling Lingkaran")
print("========================")
r = int(input("Masukkan Nilai r :"))
print("========================")
print("Keliling Lingkaran")
print("r:",r)
print("Rumus keliling lingkaran yaitu 2πr")
print("keliling lingkaran adalah:",2*3.14*r)
print("========================")

print("Perhitungan Luas Lingkaran")
print("========================")
r = int(input("Masukkan Nilai r :"))
print("========================")
print("Luas Lingkaran")
print("r:",r)
print("Rumus luas lingkaran yaitu πr²")
print("Hasil luas  lingkarannya adalah:",3.14*r*r)
print("========================")
